language: cpp

sudo: required
dist: bionic
osx_image: xcode11.5

addons:
  apt:
    packages:
      - autotools-dev
      - automake

script:
  - autoreconf -f -i
  - ./configure
  - make

before_install:
  - echo $LANG
  - echo $LC_ALL

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

branches:
  only:
    - master

notifications:
  email: true

