language: cpp

sudo: required
dist: trusty
osx_image: xcode10.1

addons:
  apt:
    packages:
      - autotools-dev
      - automake

script:
  - autoreconf -f -i
  - ./configure
  - make -j
  - make check 

before_install:
  - eval "${MATRIX_EVAL}"
  - echo $LANG
  - echo $LC_ALL

compiler:
  - clang
  - gcc

os:
  - linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - osx

branches:
  only:
  - master

notifications:
  email: true

