language: cpp

sudo: required
dist: trusty
osx_image: xcode8

addons:
  apt:
    packages:
      - autotools-dev
      - automake

script:
  - autoreconf -f -i
  - ./configure
  - make -j
  - make check 

before_install:
  - echo $LANG
  - echo $LC_ALL

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

branches:
  only:
  - master

notifications:
  email: true

