language: cpp

sudo: required

addons:
  apt:
    packages:
      - autotools-dev
      - automake
      - libcppunit

script:
  - autoreconf
  - ./configure && make && make check 

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install cppunit; fi

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

branches:
  only:
  - master

notifications:
  email: true

