language: cpp

before_install:
  - sudo apt-get update -q
  - sudo apt-get install aclocal-1.15 -y

compiler:
  - clang
  - gcc
dist: trusty

os:
  - linux
  - osx

branches:
  only:
  - master

notifications:
  email: true

