language: cpp

sudo: required

addons:
  apt:
    packages:
      - autotools-dev
      - automake

compiler:
  - clang
  - gcc
dist: trusty

os:
  - linux
  - osx

branches:
  only:
  - master

notifications:
  email: true

